// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Storix_BE.Domain.Context;

#nullable disable

namespace Storix_BE.Domain.Migrations
{
    [DbContext(typeof(StorixDbContext))]
    [Migration("20260128030331_UpdateTableFields")]
    partial class UpdateTableFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Storix_BE.Domain.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("character varying")
                        .HasColumnName("action");

                    b.Property<string>("Entity")
                        .HasColumnType("character varying")
                        .HasColumnName("entity");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("timestamp");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("activity_logs_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("activity_logs", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("character varying")
                        .HasColumnName("address");

                    b.Property<string>("BusinessCode")
                        .HasColumnType("character varying")
                        .HasColumnName("business_code");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("character varying")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("character varying")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .HasColumnType("character varying")
                        .HasColumnName("status");

                    b.Property<string>("SubscriptionPlan")
                        .HasColumnType("character varying")
                        .HasColumnName("subscription_plan");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("companies_pkey");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.InboundOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int?>("InboundRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("inbound_request_id");

                    b.Property<string>("ReferenceCode")
                        .HasColumnType("character varying")
                        .HasColumnName("reference_code");

                    b.Property<string>("Status")
                        .HasColumnType("character varying")
                        .HasColumnName("status");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("supplier_id");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("inbound_orders_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("InboundRequestId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("inbound_orders", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.InboundOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ExpectedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("expected_quantity");

                    b.Property<int?>("InboundOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("inbound_order_id");

                    b.Property<int?>("InboundRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("inbound_request_id");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int?>("ReceivedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("received_quantity");

                    b.HasKey("Id")
                        .HasName("inbound_order_items_pkey");

                    b.HasIndex("InboundOrderId");

                    b.HasIndex("InboundRequestId");

                    b.HasIndex("ProductId");

                    b.ToTable("inbound_order_items", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.InboundRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("approved_at");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer")
                        .HasColumnName("approved_by");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("RequestedBy")
                        .HasColumnType("integer")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .HasColumnType("character varying")
                        .HasColumnName("status");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("supplier_id");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("inbound_requests_pkey");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("RequestedBy");

                    b.HasIndex("SupplierId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("inbound_requests", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int?>("ReservedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("reserved_quantity");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("inventory_pkey");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.InventoryLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("InventoryId")
                        .HasColumnType("integer")
                        .HasColumnName("inventory_id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int?>("ShelfId")
                        .HasColumnType("integer")
                        .HasColumnName("shelf_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("inventory_locations_pkey");

                    b.HasIndex("InventoryId");

                    b.HasIndex("ShelfId");

                    b.ToTable("inventory_locations", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.InventoryTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("PerformedBy")
                        .HasColumnType("integer")
                        .HasColumnName("performed_by");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int?>("QuantityChange")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_change");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer")
                        .HasColumnName("reference_id");

                    b.Property<string>("TransactionType")
                        .HasColumnType("character varying")
                        .HasColumnName("transaction_type");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("inventory_transactions_pkey");

                    b.HasIndex("PerformedBy");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("inventory_transactions", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.NavEdge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Distance")
                        .HasColumnType("double precision")
                        .HasColumnName("distance");

                    b.Property<int?>("NodeFrom")
                        .HasColumnType("integer")
                        .HasColumnName("node_from");

                    b.Property<int?>("NodeTo")
                        .HasColumnType("integer")
                        .HasColumnName("node_to");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("nav_edge_pkey");

                    b.HasIndex("NodeFrom");

                    b.HasIndex("NodeTo");

                    b.HasIndex("WarehouseId");

                    b.ToTable("nav_edge", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.NavNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .HasColumnType("character varying")
                        .HasColumnName("type");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id");

                    b.Property<int?>("XCoordinate")
                        .HasColumnType("integer")
                        .HasColumnName("x_coordinate");

                    b.Property<int?>("YCoordinate")
                        .HasColumnType("integer")
                        .HasColumnName("y_coordinate");

                    b.HasKey("Id")
                        .HasName("nav_node_pkey");

                    b.HasIndex("WarehouseId");

                    b.ToTable("nav_node", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.OutboundOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("Destination")
                        .HasColumnType("character varying")
                        .HasColumnName("destination");

                    b.Property<string>("Note")
                        .HasColumnType("character varying")
                        .HasColumnName("note");

                    b.Property<int?>("StaffId")
                        .HasColumnType("integer")
                        .HasColumnName("staff_id");

                    b.Property<string>("Status")
                        .HasColumnType("character varying")
                        .HasColumnName("status");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("outbound_orders_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("WarehouseId");

                    b.ToTable("outbound_orders", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.OutboundOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("OutboundOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("outbound_order_id");

                    b.Property<int?>("OutboundRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("outbound_request_id");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("outbound_order_items_pkey");

                    b.HasIndex("OutboundOrderId");

                    b.HasIndex("OutboundRequestId");

                    b.HasIndex("ProductId");

                    b.ToTable("outbound_order_items", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.OutboundRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("approved_at");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer")
                        .HasColumnName("approved_by");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Destination")
                        .HasColumnType("character varying")
                        .HasColumnName("destination");

                    b.Property<int?>("RequestedBy")
                        .HasColumnType("integer")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .HasColumnType("character varying")
                        .HasColumnName("status");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("outbound_requests_pkey");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("RequestedBy");

                    b.HasIndex("WarehouseId");

                    b.ToTable("outbound_requests", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("character varying")
                        .HasColumnName("category");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .HasColumnType("character varying")
                        .HasColumnName("sku");

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<string>("Unit")
                        .HasColumnType("character varying")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("products_pkey");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TypeId");

                    b.HasIndex(new[] { "Sku" }, "products_sku_key")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("types_pkey");

                    b.ToTable("types", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("role_pkey");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.Shelf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Code")
                        .HasColumnType("character varying")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("Image")
                        .HasColumnType("character varying")
                        .HasColumnName("image");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.Property<int?>("XCoordinate")
                        .HasColumnType("integer")
                        .HasColumnName("x_coordinate");

                    b.Property<int?>("YCoordinate")
                        .HasColumnType("integer")
                        .HasColumnName("y_coordinate");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("shelves_pkey");

                    b.HasIndex("ZoneId");

                    b.ToTable("shelves", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.ShelfLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("character varying")
                        .HasColumnName("code");

                    b.Property<int?>("ShelfId")
                        .HasColumnType("integer")
                        .HasColumnName("shelf_id");

                    b.HasKey("Id")
                        .HasName("shelf_levels_pkey");

                    b.HasIndex("ShelfId");

                    b.ToTable("shelf_levels", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.ShelfLevelBin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("character varying")
                        .HasColumnName("code");

                    b.Property<double?>("Height")
                        .HasColumnType("double precision")
                        .HasColumnName("height");

                    b.Property<int?>("InventoryId")
                        .HasColumnType("integer")
                        .HasColumnName("inventory_id");

                    b.Property<int?>("LevelId")
                        .HasColumnType("integer")
                        .HasColumnName("level_id");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<double?>("Width")
                        .HasColumnType("double precision")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("shelf_level_bins_pkey");

                    b.HasIndex("InventoryId");

                    b.HasIndex("LevelId");

                    b.ToTable("shelf_level_bins", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.ShelfNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("NodeId")
                        .HasColumnType("integer")
                        .HasColumnName("node_id");

                    b.Property<int?>("ShelfId")
                        .HasColumnType("integer")
                        .HasColumnName("shelf_id");

                    b.HasKey("Id")
                        .HasName("shelf_node_pkey");

                    b.HasIndex("NodeId");

                    b.HasIndex("ShelfId");

                    b.ToTable("shelf_node", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.StockCountItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("counted_quantity");

                    b.Property<string>("Description")
                        .HasColumnType("character varying")
                        .HasColumnName("description");

                    b.Property<int?>("Discrepancy")
                        .HasColumnType("integer")
                        .HasColumnName("discrepancy");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<int?>("StockCountId")
                        .HasColumnType("integer")
                        .HasColumnName("stock_count_id");

                    b.Property<int?>("SystemQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("system_quantity");

                    b.HasKey("Id")
                        .HasName("stock_count_items_pkey");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockCountId");

                    b.ToTable("stock_count_items", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.StockCountsTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_to");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("character varying")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ExecutedDay")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("executed_day");

                    b.Property<DateTime?>("FinishedDay")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("finished_day");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<int?>("PerformedBy")
                        .HasColumnType("integer")
                        .HasColumnName("performed_by");

                    b.Property<string>("Status")
                        .HasColumnType("character varying")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .HasColumnType("character varying")
                        .HasColumnName("type");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("stock_counts_tickets_pkey");

                    b.HasIndex("PerformedBy");

                    b.HasIndex("WarehouseId");

                    b.ToTable("stock_counts_tickets", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.StorageForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DaysToStockout")
                        .HasColumnType("integer")
                        .HasColumnName("days_to_stockout");

                    b.Property<int?>("PredictedStock")
                        .HasColumnType("integer")
                        .HasColumnName("predicted_stock");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("RecommendedAction")
                        .HasColumnType("character varying")
                        .HasColumnName("recommended_action");

                    b.Property<string>("RiskLevel")
                        .HasColumnType("character varying")
                        .HasColumnName("risk_level");

                    b.Property<string>("TypeOfForecast")
                        .HasColumnType("character varying")
                        .HasColumnName("type_of_forecast");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("storage_forecasts_pkey");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("storage_forecasts", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.StorageRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("InboundProductId")
                        .HasColumnType("integer")
                        .HasColumnName("inbound_product_id");

                    b.Property<string>("Reason")
                        .HasColumnType("character varying")
                        .HasColumnName("reason");

                    b.Property<string>("StorageRecommendation1")
                        .HasColumnType("character varying")
                        .HasColumnName("storage_recommendation");

                    b.HasKey("Id")
                        .HasName("storage_recommendations_pkey");

                    b.HasIndex("InboundProductId");

                    b.ToTable("storage_recommendations", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.StorageZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("character varying")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Image")
                        .HasColumnType("character varying")
                        .HasColumnName("image");

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("storage_zones_pkey");

                    b.HasIndex("TypeId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("storage_zones", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("character varying")
                        .HasColumnName("address");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("character varying")
                        .HasColumnName("contact_person");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("character varying")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("character varying")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .HasColumnType("character varying")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("suppliers_pkey");

                    b.HasIndex("CompanyId");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.TransferOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int?>("DestinationWarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("destination_warehouse_id");

                    b.Property<int?>("SourceWarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("source_warehouse_id");

                    b.Property<string>("Status")
                        .HasColumnType("character varying")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("transfer_orders_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DestinationWarehouseId");

                    b.HasIndex("SourceWarehouseId");

                    b.ToTable("transfer_orders", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.TransferOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int?>("TransferOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("transfer_order_id");

                    b.HasKey("Id")
                        .HasName("transfer_order_items_pkey");

                    b.HasIndex("ProductId");

                    b.HasIndex("TransferOrderId");

                    b.ToTable("transfer_order_items", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("character varying")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasColumnType("character varying")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("character varying")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("character varying")
                        .HasColumnName("phone");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .HasColumnType("character varying")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("character varying")
                        .HasColumnName("address");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("GridSize")
                        .HasColumnType("integer")
                        .HasColumnName("grid_size");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("Image")
                        .HasColumnType("character varying")
                        .HasColumnName("image");

                    b.Property<int?>("Length")
                        .HasColumnType("integer")
                        .HasColumnName("length");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .HasColumnType("character varying")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("warehouses_pkey");

                    b.HasIndex("CompanyId");

                    b.ToTable("warehouses", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.WarehouseAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("assigned_at");

                    b.Property<string>("RoleInWarehouse")
                        .HasColumnType("character varying")
                        .HasColumnName("role_in_warehouse");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("warehouse_assignments_pkey");

                    b.HasIndex("UserId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("warehouse_assignments", (string)null);
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.ActivityLog", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_activity_logs_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.InboundOrder", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.User", "CreatedByNavigation")
                        .WithMany("InboundOrders")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("fk_inbound_orders_created_by");

                    b.HasOne("Storix_BE.Domain.Models.InboundRequest", "InboundRequest")
                        .WithMany("InboundOrders")
                        .HasForeignKey("InboundRequestId")
                        .HasConstraintName("fk_inbound_orders_inbound_request_id");

                    b.HasOne("Storix_BE.Domain.Models.Supplier", "Supplier")
                        .WithMany("InboundOrders")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("fk_inbound_orders_supplier_id");

                    b.HasOne("Storix_BE.Domain.Models.Warehouse", "Warehouse")
                        .WithMany("InboundOrders")
                        .HasForeignKey("WarehouseId")
                        .HasConstraintName("fk_inbound_orders_warehouse_id");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("InboundRequest");

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.InboundOrderItem", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.InboundOrder", "InboundOrder")
                        .WithMany("InboundOrderItems")
                        .HasForeignKey("InboundOrderId")
                        .HasConstraintName("fk_inbound_order_items_inbound_order_id");

                    b.HasOne("Storix_BE.Domain.Models.InboundRequest", "InboundRequest")
                        .WithMany("InboundOrderItems")
                        .HasForeignKey("InboundRequestId")
                        .HasConstraintName("fk_inbound_order_items_inbound_request_id");

                    b.HasOne("Storix_BE.Domain.Models.Product", "Product")
                        .WithMany("InboundOrderItems")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_inbound_order_items_product_id");

                    b.Navigation("InboundOrder");

                    b.Navigation("InboundRequest");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.InboundRequest", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.User", "ApprovedByNavigation")
                        .WithMany("InboundRequestApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("fk_inbound_requests_approved_by");

                    b.HasOne("Storix_BE.Domain.Models.User", "RequestedByNavigation")
                        .WithMany("InboundRequestRequestedByNavigations")
                        .HasForeignKey("RequestedBy")
                        .HasConstraintName("fk_inbound_requests_requested_by");

                    b.HasOne("Storix_BE.Domain.Models.Supplier", "Supplier")
                        .WithMany("InboundRequests")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("fk_inbound_requests_supplier_id");

                    b.HasOne("Storix_BE.Domain.Models.Warehouse", "Warehouse")
                        .WithMany("InboundRequests")
                        .HasForeignKey("WarehouseId")
                        .HasConstraintName("fk_inbound_requests_warehouse_id");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("RequestedByNavigation");

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.Inventory", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_inventory_product_id");

                    b.HasOne("Storix_BE.Domain.Models.Warehouse", "Warehouse")
                        .WithMany("Inventories")
                        .HasForeignKey("WarehouseId")
                        .HasConstraintName("fk_inventory_warehouse_id");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.InventoryLocation", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.Inventory", "Inventory")
                        .WithMany("InventoryLocations")
                        .HasForeignKey("InventoryId")
                        .HasConstraintName("fk_inventory_locations_inventory_id");

                    b.HasOne("Storix_BE.Domain.Models.Shelf", "Shelf")
                        .WithMany("InventoryLocations")
                        .HasForeignKey("ShelfId")
                        .HasConstraintName("fk_inventory_locations_shelf_id");

                    b.Navigation("Inventory");

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.InventoryTransaction", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.User", "PerformedByNavigation")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("PerformedBy")
                        .HasConstraintName("fk_inventory_transactions_performed_by");

                    b.HasOne("Storix_BE.Domain.Models.Product", "Product")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_inventory_transactions_product_id");

                    b.HasOne("Storix_BE.Domain.Models.Warehouse", "Warehouse")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("WarehouseId")
                        .HasConstraintName("fk_inventory_transactions_warehouse_id");

                    b.Navigation("PerformedByNavigation");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.NavEdge", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.NavNode", "NodeFromNavigation")
                        .WithMany("NavEdgeNodeFromNavigations")
                        .HasForeignKey("NodeFrom")
                        .HasConstraintName("fk_nav_edge_node_from");

                    b.HasOne("Storix_BE.Domain.Models.NavNode", "NodeToNavigation")
                        .WithMany("NavEdgeNodeToNavigations")
                        .HasForeignKey("NodeTo")
                        .HasConstraintName("fk_nav_edge_node_to");

                    b.HasOne("Storix_BE.Domain.Models.Warehouse", "Warehouse")
                        .WithMany("NavEdges")
                        .HasForeignKey("WarehouseId")
                        .HasConstraintName("fk_nav_edge_warehouse_id");

                    b.Navigation("NodeFromNavigation");

                    b.Navigation("NodeToNavigation");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.NavNode", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.Warehouse", "Warehouse")
                        .WithMany("NavNodes")
                        .HasForeignKey("WarehouseId")
                        .HasConstraintName("fk_nav_node_warehouse_id");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.OutboundOrder", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.User", "CreatedByNavigation")
                        .WithMany("OutboundOrders")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("fk_outbound_orders_created_by");

                    b.HasOne("Storix_BE.Domain.Models.Warehouse", "Warehouse")
                        .WithMany("OutboundOrders")
                        .HasForeignKey("WarehouseId")
                        .HasConstraintName("fk_outbound_orders_warehouse_id");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.OutboundOrderItem", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.OutboundOrder", "OutboundOrder")
                        .WithMany("OutboundOrderItems")
                        .HasForeignKey("OutboundOrderId")
                        .HasConstraintName("fk_outbound_order_items_outbound_order_id");

                    b.HasOne("Storix_BE.Domain.Models.OutboundRequest", "OutboundRequest")
                        .WithMany("OutboundOrderItems")
                        .HasForeignKey("OutboundRequestId")
                        .HasConstraintName("fk_outbound_order_items_outbound_request_id");

                    b.HasOne("Storix_BE.Domain.Models.Product", "Product")
                        .WithMany("OutboundOrderItems")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_outbound_order_items_product_id");

                    b.Navigation("OutboundOrder");

                    b.Navigation("OutboundRequest");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.OutboundRequest", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.User", "ApprovedByNavigation")
                        .WithMany("OutboundRequestApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("fk_outbound_requests_approved_by");

                    b.HasOne("Storix_BE.Domain.Models.User", "RequestedByNavigation")
                        .WithMany("OutboundRequestRequestedByNavigations")
                        .HasForeignKey("RequestedBy")
                        .HasConstraintName("fk_outbound_requests_requested_by");

                    b.HasOne("Storix_BE.Domain.Models.Warehouse", "Warehouse")
                        .WithMany("OutboundRequests")
                        .HasForeignKey("WarehouseId")
                        .HasConstraintName("fk_outbound_requests_warehouse_id");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("RequestedByNavigation");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.Product", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.Company", "Company")
                        .WithMany("Products")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("fk_products_company_id");

                    b.HasOne("Storix_BE.Domain.Models.ProductType", "Type")
                        .WithMany("Products")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("fk_products_type_id");

                    b.Navigation("Company");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.Shelf", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.StorageZone", "Zone")
                        .WithMany("Shelves")
                        .HasForeignKey("ZoneId")
                        .HasConstraintName("fk_shelves_zone_id");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.ShelfLevel", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.Shelf", "Shelf")
                        .WithMany("ShelfLevels")
                        .HasForeignKey("ShelfId")
                        .HasConstraintName("fk_shelf_levels_shelf_id");

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.ShelfLevelBin", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.Inventory", "Inventory")
                        .WithMany("ShelfLevelBins")
                        .HasForeignKey("InventoryId")
                        .HasConstraintName("fk_shelf_level_bins_inventory_id");

                    b.HasOne("Storix_BE.Domain.Models.ShelfLevel", "Level")
                        .WithMany("ShelfLevelBins")
                        .HasForeignKey("LevelId")
                        .HasConstraintName("fk_shelf_level_bins_level_id");

                    b.Navigation("Inventory");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.ShelfNode", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.NavNode", "Node")
                        .WithMany("ShelfNodes")
                        .HasForeignKey("NodeId")
                        .HasConstraintName("fk_shelf_node_node_id");

                    b.HasOne("Storix_BE.Domain.Models.Shelf", "Shelf")
                        .WithMany("ShelfNodes")
                        .HasForeignKey("ShelfId")
                        .HasConstraintName("fk_shelf_node_shelf_id");

                    b.Navigation("Node");

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.StockCountItem", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.Product", "Product")
                        .WithMany("StockCountItems")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_stock_count_items_product_id");

                    b.HasOne("Storix_BE.Domain.Models.StockCountsTicket", "StockCount")
                        .WithMany("StockCountItems")
                        .HasForeignKey("StockCountId")
                        .HasConstraintName("fk_stock_count_items_stock_count_id");

                    b.Navigation("Product");

                    b.Navigation("StockCount");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.StockCountsTicket", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.User", "PerformedByNavigation")
                        .WithMany("StockCountsTickets")
                        .HasForeignKey("PerformedBy")
                        .HasConstraintName("fk_stock_counts_tickets_performed_by");

                    b.HasOne("Storix_BE.Domain.Models.Warehouse", "Warehouse")
                        .WithMany("StockCountsTickets")
                        .HasForeignKey("WarehouseId")
                        .HasConstraintName("fk_stock_counts_tickets_warehouse_id");

                    b.Navigation("PerformedByNavigation");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.StorageForecast", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.Product", "Product")
                        .WithMany("StorageForecasts")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_storage_forecasts_product_id");

                    b.HasOne("Storix_BE.Domain.Models.Warehouse", "Warehouse")
                        .WithMany("StorageForecasts")
                        .HasForeignKey("WarehouseId")
                        .HasConstraintName("fk_storage_forecasts_warehouse_id");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.StorageRecommendation", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.InboundOrderItem", "InboundProduct")
                        .WithMany("StorageRecommendations")
                        .HasForeignKey("InboundProductId")
                        .HasConstraintName("fk_storage_recommendations_inbound_product_id");

                    b.Navigation("InboundProduct");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.StorageZone", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.ProductType", "Type")
                        .WithMany("StorageZones")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("fk_storage_zones_type_id");

                    b.HasOne("Storix_BE.Domain.Models.Warehouse", "Warehouse")
                        .WithMany("StorageZones")
                        .HasForeignKey("WarehouseId")
                        .HasConstraintName("fk_storage_zones_warehouse_id");

                    b.Navigation("Type");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.Supplier", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.Company", "Company")
                        .WithMany("Suppliers")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("fk_suppliers_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.TransferOrder", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.User", "CreatedByNavigation")
                        .WithMany("TransferOrders")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("fk_transfer_orders_created_by");

                    b.HasOne("Storix_BE.Domain.Models.Warehouse", "DestinationWarehouse")
                        .WithMany("TransferOrderDestinationWarehouses")
                        .HasForeignKey("DestinationWarehouseId")
                        .HasConstraintName("fk_transfer_orders_destination_warehouse_id");

                    b.HasOne("Storix_BE.Domain.Models.Warehouse", "SourceWarehouse")
                        .WithMany("TransferOrderSourceWarehouses")
                        .HasForeignKey("SourceWarehouseId")
                        .HasConstraintName("fk_transfer_orders_source_warehouse_id");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DestinationWarehouse");

                    b.Navigation("SourceWarehouse");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.TransferOrderItem", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.Product", "Product")
                        .WithMany("TransferOrderItems")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_transfer_order_items_product_id");

                    b.HasOne("Storix_BE.Domain.Models.TransferOrder", "TransferOrder")
                        .WithMany("TransferOrderItems")
                        .HasForeignKey("TransferOrderId")
                        .HasConstraintName("fk_transfer_order_items_transfer_order_id");

                    b.Navigation("Product");

                    b.Navigation("TransferOrder");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.User", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("fk_users_company_id");

                    b.HasOne("Storix_BE.Domain.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_users_role_id");

                    b.Navigation("Company");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.Warehouse", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.Company", "Company")
                        .WithMany("Warehouses")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("fk_warehouses_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.WarehouseAssignment", b =>
                {
                    b.HasOne("Storix_BE.Domain.Models.User", "User")
                        .WithMany("WarehouseAssignments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_warehouse_assignments_user_id");

                    b.HasOne("Storix_BE.Domain.Models.Warehouse", "Warehouse")
                        .WithMany("WarehouseAssignments")
                        .HasForeignKey("WarehouseId")
                        .HasConstraintName("fk_warehouse_assignments_warehouse_id");

                    b.Navigation("User");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.Company", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Suppliers");

                    b.Navigation("Users");

                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.InboundOrder", b =>
                {
                    b.Navigation("InboundOrderItems");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.InboundOrderItem", b =>
                {
                    b.Navigation("StorageRecommendations");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.InboundRequest", b =>
                {
                    b.Navigation("InboundOrderItems");

                    b.Navigation("InboundOrders");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.Inventory", b =>
                {
                    b.Navigation("InventoryLocations");

                    b.Navigation("ShelfLevelBins");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.NavNode", b =>
                {
                    b.Navigation("NavEdgeNodeFromNavigations");

                    b.Navigation("NavEdgeNodeToNavigations");

                    b.Navigation("ShelfNodes");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.OutboundOrder", b =>
                {
                    b.Navigation("OutboundOrderItems");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.OutboundRequest", b =>
                {
                    b.Navigation("OutboundOrderItems");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.Product", b =>
                {
                    b.Navigation("InboundOrderItems");

                    b.Navigation("Inventories");

                    b.Navigation("InventoryTransactions");

                    b.Navigation("OutboundOrderItems");

                    b.Navigation("StockCountItems");

                    b.Navigation("StorageForecasts");

                    b.Navigation("TransferOrderItems");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.ProductType", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("StorageZones");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.Shelf", b =>
                {
                    b.Navigation("InventoryLocations");

                    b.Navigation("ShelfLevels");

                    b.Navigation("ShelfNodes");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.ShelfLevel", b =>
                {
                    b.Navigation("ShelfLevelBins");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.StockCountsTicket", b =>
                {
                    b.Navigation("StockCountItems");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.StorageZone", b =>
                {
                    b.Navigation("Shelves");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.Supplier", b =>
                {
                    b.Navigation("InboundOrders");

                    b.Navigation("InboundRequests");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.TransferOrder", b =>
                {
                    b.Navigation("TransferOrderItems");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("InboundOrders");

                    b.Navigation("InboundRequestApprovedByNavigations");

                    b.Navigation("InboundRequestRequestedByNavigations");

                    b.Navigation("InventoryTransactions");

                    b.Navigation("OutboundOrders");

                    b.Navigation("OutboundRequestApprovedByNavigations");

                    b.Navigation("OutboundRequestRequestedByNavigations");

                    b.Navigation("StockCountsTickets");

                    b.Navigation("TransferOrders");

                    b.Navigation("WarehouseAssignments");
                });

            modelBuilder.Entity("Storix_BE.Domain.Models.Warehouse", b =>
                {
                    b.Navigation("InboundOrders");

                    b.Navigation("InboundRequests");

                    b.Navigation("Inventories");

                    b.Navigation("InventoryTransactions");

                    b.Navigation("NavEdges");

                    b.Navigation("NavNodes");

                    b.Navigation("OutboundOrders");

                    b.Navigation("OutboundRequests");

                    b.Navigation("StockCountsTickets");

                    b.Navigation("StorageForecasts");

                    b.Navigation("StorageZones");

                    b.Navigation("TransferOrderDestinationWarehouses");

                    b.Navigation("TransferOrderSourceWarehouses");

                    b.Navigation("WarehouseAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
